---

- name: install fedora epel repository
  yum:
    name: 'https://pkg.adfinis-sygroup.ch/epel//epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm'
    state: present
  when: ansible_distribution == 'RedHat'

- name: deactivate the epel repository
  yum_repository:
    name: epel
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    description: Fedora EPEL
    enabled: no
  when: ansible_distribution == 'RedHat'

- name: Import EPEL GPG key.
  rpm_key:
    key: '/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}'
    state: present
  when: ansible_distribution == 'RedHat'
  ignore_errors: '{{ ansible_check_mode }}'

- name: install icinga apt key
  apt_key:
    url: '{{ icinga2_agent_apt.key }}'
    state: present
  when: ansible_os_family == 'Debian'

- name: configure icinga apt repository
  apt_repository:
    repo: '{{ icinga2_agent_apt.repo }}'
    state: present
  when: ansible_os_family == 'Debian'

- name: configure icinga epel repository
  yum_repository:
    name: icinga-stable-release
    description: icinga2 latest repository
    baseurl: '{{ icinga2_agent_yum.repo }}'
    gpgkey: '{{ icinga2_agent_yum.key }}'
  when: ansible_os_family == 'RedHat'

- name: install icinga 2 agent packages
  package:
    name: '{{ icinga2_agent_packages }}'
    state: present
